apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*

build:
  local:
    push: false
  artifacts:
    - image: dishenmakwana/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .

    - image: dishenmakwana/comments
      context: comments
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: . 

    - image: dishenmakwana/event-bus
      context: event-bus
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .  

    - image: dishenmakwana/moderation
      context: moderation
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .

    - image: dishenmakwana/posts
      context: posts
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .

    - image: dishenmakwana/query
      context: query
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
  